# Generated by Django 2.0.5 on 2018-05-25 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSalaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_salary_finger', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('picture', models.ImageField(default='img/salary/default.png', null=True, upload_to='img/salary')),
                ('date_joined', models.DateField()),
                ('group_salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.GroupSalaries')),
            ],
        ),
    ]
