# Generated by Django 2.0.5 on 2018-05-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
