# Generated by Django 2.0.5 on 2018-05-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180526_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='picture',
            field=models.ImageField(blank=True, default='img/salary/default.png', null=True, upload_to='img/salary'),
        ),
    ]
