# Generated by Django 2.0.5 on 2018-05-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180526_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='picture',
        ),
    ]
