# Generated by Django 2.0.5 on 2018-05-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_salary_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='phone',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='salary',
            name='picture',
            field=models.ImageField(blank=True, default='img/salary/default.png', null=True, upload_to='img/salary'),
        ),
    ]
