# Generated by Django 2.0.5 on 2018-05-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20180528_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='picture',
        ),
        migrations.AlterField(
            model_name='salary',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
